### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by ddehghan** [honza/django-chef#1]
Hi Honza,

I am running into this issue. I think you ran into it as well on another thread. I am not sure if you were able to resolve it or not. 

I am running this on lucid 64.

I cloned your repo and did a vagrant up.

Any help would be much appreciated. 

Thanks
David

[default] Importing base box 'base'...
[default] The guest additions on this VM do not match the install version of
VirtualBox! This may cause things such as forwarded ports, shared
folders, and more to not work properly. If any of those things fail on
this machine, please update the guest additions and repackage the
box.

Guest Additions Version: 4.1.0
VirtualBox Version: 4.1.2
[default] Matching MAC address for NAT networking...
[default] Clearing any previously set forwarded ports...
[default] Forwarding ports...
[default] -- ssh: 22 => 2222 (adapter 1)
[default] -- http: 80 => 8080 (adapter 1)
[default] -- web: 9999 => 9999 (adapter 1)
[default] Creating shared folders metadata...
[default] Running any VM customizations...
[default] Booting VM...
[default] Waiting for VM to boot. This can take a few minutes.
[default] VM booted and ready for use!
[default] Mounting shared folders...
[default] -- v-root: /vagrant
[default] -- v-csc-1: /tmp/vagrant-chef-1/chef-solo-1
[default] Running provisioner: Vagrant::Provisioners::ChefSolo...
[default] Generating chef JSON and uploading...
[default] Running chef-solo...
[default] stdin: is not a tty
: stderr
[default] [Sun, 20 Nov 2011 04:47:00 -0800] INFO: **\* Chef 0.10.2 ***
: stdout
[default] [Sun, 20 Nov 2011 04:47:01 -0800] INFO: Setting the run_list to ["recipe[djangoapp::default]"] from JSON
: stdout
[default] [Sun, 20 Nov 2011 04:47:01 -0800] INFO: Run List is [recipe[djangoapp::default]]
: stdout
[default] [Sun, 20 Nov 2011 04:47:01 -0800] INFO: Run List expands to [djangoapp::default]
[Sun, 20 Nov 2011 04:47:01 -0800] INFO: Starting Chef Run for lucid64
: stdout
[default] [Sun, 20 Nov 2011 04:47:02 -0800] ERROR: Running exception handlers
: stdout
[default] [Sun, 20 Nov 2011 04:47:02 -0800] ERROR: Exception handlers complete
: stdout
[default] [Sun, 20 Nov 2011 04:47:02 -0800] FATAL: Stacktrace dumped to /tmp/vagrant-chef-1/chef-stacktrace.out
: stdout
[default] [Sun, 20 Nov 2011 04:47:02 -0800] FATAL: NoMethodError: undefined method `apt_repository' for #Chef::Recipe:0x7f84d1871e20
: stdout
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chef-solo -c /tmp/vagrant-chef-1/solo.rb -j /tmp/vagrant-chef-1/dna.json

The output of the command prior to failing is outputted below:

[no output]

**Comment by honza** [comment]
I will try to reproduce. Give me a few hours, hopefully I can manage to get that done.

**Comment by ddehghan** [comment]
that would be great. :-)

On Sun, Nov 20, 2011 at 1:56 PM, Honza Pokorny <
reply@reply.github.com

**Comment by honza** [comment]
It looks like RabbitMQ was broken, so I removed it. Commit d78433dd3c8a66953f5cb268c99d36b72a478dea fixes it. At work, we've been using Redis as the celery backend --- I might add that in the future. Let me know if you get it to work. Thanks

**Comment by ddehghan** [comment]
Yeah. Thank you . That fixed it. 

A suggestion: Maybe you can put up a simple hello world page in the coolname project so that we can easily see the VM working. It is easier to build on top of a project that verifiable works for a simple example.
