### ISSUE TITLE
symlink to /opt directory

### ISSUE THREAD

**Issue by akiokio** [honza/django-chef#3]
Hello Honza,

First, tanks for the repository I've been using for some of my projects and works pretty great.

I've only one doubt, in the read-me you say:

> The source code on the host machine is symlinked to the /opt directory.

Can you tell me where in the configuration you do the symlink?

**Comment by honza** [comment]
I think this refers to the `ln` command in the `fabfile` found [here](https://github.com/honza/django-chef/blob/c7e817220ef70b42dc710165cd086b5ba7687d3b/fabfile.py#L111). But you're right, it's probably misleading. It actually links it to a directory deep in the `/opt` one.

How do you think this should be improved?

**Comment by akiokio** [comment]
I see now,

I use your project a little bit different, instead symlinking the /vagrant/src to the opt folder I just use the /vagrant/src directly by running the django server in this folder.

I also use pycharm and works very well with this box :)

**Comment by honza** [comment]
Excellent, that works, too.

The benefit of using `/opt` is of course the fact that once your application gets deployed to a real server (ie not vagrant), you can continue using the same paths as before.
